version: '3.5'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - '6500:5432'
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

  app:
    build: 
      context: .
      dockerfile: .docker/Dockerfile
    container_name: evento-app
    command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; ls; uvicorn evento.main:app --host 0.0.0.0'
    ports:
      - 8010:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
    

volumes:
  postgres-db: