"""modify_user_password_column_name

Revision ID: 8d4ee2fa1d97
Revises: 6424ccb9caa3
Create Date: 2023-03-10 23:13:42.909064

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "8d4ee2fa1d97"
down_revision = "6424ccb9caa3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "hash_password", new_column_name="password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "password", new_column_name="hash_password")
    # ### end Alembic commands ###
