"""add_relation_with_event_category

Revision ID: 758c6cddb341
Revises: 3171ba91f8d3
Create Date: 2023-03-11 01:47:16.820830

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '758c6cddb341'
down_revision = '3171ba91f8d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events_to_event_categories',
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('event_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_category_id'], ['event_categories.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], )
    )
    op.drop_column('events', 'categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('categories', postgresql.ARRAY(postgresql.ENUM('CINEMA', 'DEVELOPMENT', 'ENTARTAINMENT', 'CONCERT', 'SPORT', 'ART', 'WORLD_EVENT', 'WORKSHOP', 'TOUR', 'TRIP', name='category')), autoincrement=False, nullable=False))
    op.drop_table('events_to_event_categories')
    op.drop_table('event_categories')
    # ### end Alembic commands ###
