"""add_relation_with_images

Revision ID: 3171ba91f8d3
Revises: 8d4ee2fa1d97
Create Date: 2023-03-11 00:05:05.597082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3171ba91f8d3'
down_revision = '8d4ee2fa1d97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_images', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'event_images', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_images', type_='foreignkey')
    op.drop_column('event_images', 'event_id')
    # ### end Alembic commands ###
